version: '3'

services:
  smart-home:
    build: .
    restart: 'unless-stopped'
    volumes:
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - ./config.yaml:/app/config.yaml